'use client'

import { Image as ImageIcon, Loader2, XCircle } from 'lucide-react'

interface LoadingStateProps {
  className?: string
}

export function LoadingState({ className = '' }: LoadingStateProps): React.ReactElement {
  return (
    <div className={`flex-1 flex items-center justify-center ${className}`}>
      <Loader2 className="w-8 h-8 text-outrun-500 animate-spin" />
    </div>
  )
}

interface ErrorStateProps {
  error: Error | unknown
  onRetry: () => void
  className?: string
  title?: string
}

export function ErrorState({
  error,
  onRetry,
  className = '',
  title = 'Failed to load mockups',
}: ErrorStateProps): React.ReactElement {
  return (
    <div className={`flex-1 flex items-center justify-center ${className}`}>
      <div className="card p-8 text-center max-w-md">
        <XCircle className="w-10 h-10 text-rose-500 mx-auto mb-4" />
        <p className="text-white mb-2">{title}</p>
        <p className="text-slate-400 text-sm mb-4">
          {error instanceof Error ? error.message : 'Unknown error'}
        </p>
        <button onClick={onRetry} className="btn-primary">
          Retry
        </button>
      </div>
    </div>
  )
}

interface EmptyStateProps {
  className?: string
  title?: string
  description?: string
}

export function EmptyState({
  className = '',
  title = 'No mockups yet',
  description = 'Design mockups will appear here when generated by /polish_it or the design workflow.',
}: EmptyStateProps): React.ReactElement {
  return (
    <div className={`flex-1 flex items-center justify-center ${className}`}>
      <div className="card p-8 text-center max-w-md">
        <ImageIcon className="w-10 h-10 text-slate-500 mx-auto mb-4" />
        <h2 className="text-white font-medium mb-2">{title}</h2>
        <p className="text-slate-400 text-sm">{description}</p>
      </div>
    </div>
  )
}
