#!/bin/bash
# SummitFlow Ecosystem — Self-Hosting Installer
# Usage: curl -fsSL https://raw.githubusercontent.com/summitflow-solutions/summitflow/main/docker/install.sh | bash
set -euo pipefail

COMPOSE_VERSION="latest"
INSTALL_DIR="${INSTALL_DIR:-$HOME/summitflow-docker}"

echo "============================================"
echo "  SummitFlow Ecosystem — Self-Host Installer"
echo "============================================"
echo ""

# ─── Prerequisites ───────────────────────────────────────────────

check_command() {
  if ! command -v "$1" &>/dev/null; then
    echo "ERROR: $1 is not installed."
    echo "Install it and re-run this script."
    exit 1
  fi
}

check_command docker
check_command curl
check_command openssl
check_command jq

# Verify Docker Compose v2
if ! docker compose version &>/dev/null; then
  echo "ERROR: Docker Compose v2 plugin not found."
  echo "Install Docker Compose: https://docs.docker.com/compose/install/"
  exit 1
fi

echo "Docker: $(docker --version)"
echo "Compose: $(docker compose version)"
echo ""

# ─── Profile Selection ───────────────────────────────────────────

echo "Which projects do you want to run?"
echo "  1) SummitFlow only"
echo "  2) SummitFlow + Agent Hub"
echo "  3) Full stack (all projects)"
echo ""
read -rp "Select [1-3, default: 3]: " CHOICE
CHOICE="${CHOICE:-3}"

case "$CHOICE" in
  1) PROFILE="summitflow" ;;
  2) PROFILE="summitflow --profile agent-hub" ;;
  3) PROFILE="full" ;;
  *) echo "Invalid choice"; exit 1 ;;
esac

# ─── Generate Passwords ─────────────────────────────────────────

gen_password() {
  openssl rand -base64 24 | tr -d '/+=' | head -c 24
}

gen_secret() {
  openssl rand -base64 32
}

POSTGRES_PASSWORD=$(gen_password)
SF_DB_PASSWORD=$(gen_password)
AH_DB_PASSWORD=$(gen_password)
PA_DB_PASSWORD=$(gen_password)
REDIS_PASSWORD=$(gen_password)
AGENT_HUB_ENCRYPTION_KEY=$(gen_secret)
AGENT_HUB_SECRET_KEY=$(gen_secret)
INTERNAL_SERVICE_SECRET=$(gen_secret)

# ─── Setup Directory ────────────────────────────────────────────

echo ""
echo "Installing to: $INSTALL_DIR"
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

# Download compose files
REPO_BASE="https://raw.githubusercontent.com/summitflow-solutions/summitflow/main/docker/compose"
echo "Downloading compose files..."
curl -fsSL "$REPO_BASE/docker-compose.yml" -o docker-compose.yml
curl -fsSL "$REPO_BASE/init-db.sh" -o init-db.sh
curl -fsSL "$REPO_BASE/redis.conf" -o redis.conf
curl -fsSL "$REPO_BASE/.env.example" -o .env.example

# Download schema SQL files
for schema in summitflow-schema.sql agent-hub-schema.sql portfolio-ai-schema.sql; do
  echo "  Downloading $schema..."
  curl -fsSL "$REPO_BASE/$schema" -o "$schema" 2>/dev/null || echo "  Warning: $schema not found (may not be needed for your profile)"
done

chmod +x init-db.sh

# ─── Generate .env ───────────────────────────────────────────────

cat > .env <<EOF
# Generated by SummitFlow installer on $(date -Iseconds)

# ─── Infrastructure ──────────────────────────────────────────────
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
SF_DB_PASSWORD=$SF_DB_PASSWORD
AH_DB_PASSWORD=$AH_DB_PASSWORD
PA_DB_PASSWORD=$PA_DB_PASSWORD
REDIS_PASSWORD=$REDIS_PASSWORD
TAG=latest
HATCHET_TAG=latest

# ─── Host Configuration ─────────────────────────────────────────
HOST_HOME_PATH=$HOME

# ─── Backup / SMB ───────────────────────────────────────────────
# Set these to your SMB backup target
SMB_HOST=
SMB_SHARE=

# ─── Agent Hub Secrets ───────────────────────────────────────────
AGENT_HUB_ENCRYPTION_KEY=$AGENT_HUB_ENCRYPTION_KEY
AGENT_HUB_SECRET_KEY=$AGENT_HUB_SECRET_KEY
INTERNAL_SERVICE_SECRET=$INTERNAL_SERVICE_SECRET

# ─── Client Credentials (auto-generated below) ──────────────────
SUMMITFLOW_CLIENT_ID=
SUMMITFLOW_REQUEST_SOURCE=summitflow
AGENT_HUB_DASHBOARD_CLIENT_ID=
AGENT_HUB_DASHBOARD_REQUEST_SOURCE=agent-hub-dashboard
PORTFOLIO_CLIENT_ID=
PORTFOLIO_REQUEST_SOURCE=portfolio-ai
MONKEY_FIGHT_CLIENT_ID=
MONKEY_FIGHT_REQUEST_SOURCE=monkey-fight

# ─── Hatchet (auto-generated below) ─────────────────────────────
HATCHET_CLIENT_TOKEN=

# ─── Optional API Keys ──────────────────────────────────────────
# ANTHROPIC_API_KEY=
# OPENAI_API_KEY=
EOF

echo "Generated .env with random passwords and secrets"

# ─── Pull & Start ───────────────────────────────────────────────

echo ""
echo "Pulling images (this may take a few minutes)..."
docker compose --profile "$PROFILE" pull

echo ""
echo "Starting services..."
docker compose --profile "$PROFILE" up -d

# ─── Wait for Health ────────────────────────────────────────────

echo ""
echo "Waiting for services to become healthy..."

wait_for_service() {
  local name="$1" url="$2" max_wait="${3:-120}"
  for i in $(seq 1 "$max_wait"); do
    if curl -sf "$url" &>/dev/null; then
      echo "  $name is healthy"
      return 0
    fi
    sleep 2
  done
  echo "  WARNING: $name did not become healthy within ${max_wait}s"
  return 1
}

wait_for_service "Hatchet" "http://localhost:8888/api/ready" 90

# ─── Auto-generate Hatchet Token ─────────────────────────────────

echo ""
echo "Generating Hatchet client token..."
TENANT_ID=$(docker compose exec -T hatchet /hatchet-admin tenant list --config /config 2>/dev/null \
  | grep -oP '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' | head -1)

if [ -z "$TENANT_ID" ]; then
  echo "  WARNING: Could not discover Hatchet tenant ID. You'll need to generate the token manually."
  echo "  Run: docker compose exec hatchet /hatchet-admin token create --config /config --tenant-id <UUID>"
else
  HATCHET_TOKEN=$(docker compose exec -T hatchet /hatchet-admin token create \
    --config /config --tenant-id "$TENANT_ID" --expiresIn 87600h 2>/dev/null | tr -d '[:space:]')

  if [ -n "$HATCHET_TOKEN" ]; then
    sed -i "s|^HATCHET_CLIENT_TOKEN=.*|HATCHET_CLIENT_TOKEN=$HATCHET_TOKEN|" .env
    echo "  Hatchet token generated and saved to .env"
  else
    echo "  WARNING: Hatchet token generation failed. Generate manually."
  fi
fi

# Restart services that need the Hatchet token
echo "Restarting services with Hatchet token..."
docker compose --profile "$PROFILE" up -d

# Wait for Agent Hub API to be ready (needed for client credential creation)
if [[ "$CHOICE" == "2" || "$CHOICE" == "3" ]]; then
  wait_for_service "Agent Hub API" "http://localhost:8003/health" 60
fi

wait_for_service "SummitFlow API" "http://localhost:8001/health" 60

# ─── Auto-generate Client Credentials ────────────────────────────

create_client() {
  local display_name="$1" env_var="$2" client_type="${3:-external}"
  local response
  response=$(curl -sf -X POST "http://localhost:8003/api/access-control/clients" \
    -H "Content-Type: application/json" \
    -d "{\"display_name\": \"$display_name\", \"client_type\": \"$client_type\"}" 2>/dev/null)

  if [ $? -eq 0 ] && [ -n "$response" ]; then
    local client_id
    client_id=$(echo "$response" | jq -r '.client_id // empty')
    if [ -n "$client_id" ]; then
      sed -i "s|^${env_var}=.*|${env_var}=$client_id|" .env
      echo "  Created client '$display_name' → $client_id"
      return 0
    fi
  fi
  echo "  WARNING: Failed to create client '$display_name'"
  return 1
}

if [[ "$CHOICE" == "2" || "$CHOICE" == "3" ]]; then
  echo ""
  echo "Creating client credentials in Agent Hub..."
  create_client "summitflow" "SUMMITFLOW_CLIENT_ID" "internal"
  create_client "agent-hub-dashboard" "AGENT_HUB_DASHBOARD_CLIENT_ID" "internal"

  if [[ "$CHOICE" == "3" ]]; then
    create_client "portfolio-ai" "PORTFOLIO_CLIENT_ID" "internal"
    create_client "monkey-fight" "MONKEY_FIGHT_CLIENT_ID" "external"
  fi

  # Restart services to pick up new client IDs
  echo "Restarting services with client credentials..."
  docker compose --profile "$PROFILE" up -d
fi

# ─── Final Health Check ──────────────────────────────────────────

echo ""
echo "Running final health checks..."
sleep 5
wait_for_service "SummitFlow API" "http://localhost:8001/health" 30 || true

if [[ "$CHOICE" == "2" || "$CHOICE" == "3" ]]; then
  wait_for_service "Agent Hub API" "http://localhost:8003/health" 30 || true
fi

# ─── Done ─────────────────────────────────────────────────────────

echo ""
echo "============================================"
echo "  Installation Complete!"
echo "============================================"
echo ""
echo "Access your services:"
echo "  SummitFlow:   http://localhost:3001"

if [[ "$CHOICE" == "2" || "$CHOICE" == "3" ]]; then
  echo "  Agent Hub:    http://localhost:3003"
fi

if [[ "$CHOICE" == "3" ]]; then
  echo "  Terminal:     http://localhost:3002"
  echo "  Portfolio AI: http://localhost:3000"
  echo "  Monkey Fight: http://localhost:4001"
fi

echo ""
echo "(Optional) Configure SMB backup target:"
echo "  Set SMB_HOST and SMB_SHARE in .env"
echo ""
echo "Management:"
echo "  Status:  docker compose ps"
echo "  Logs:    docker compose logs -f <service>"
echo "  Stop:    docker compose down"
echo "  Update:  docker compose pull && docker compose up -d"
echo ""
echo "Config:    $INSTALL_DIR/.env"
echo "Data:      Docker volumes (pgdata, redis-data)"
echo ""
