#!/bin/bash
# SummitFlow Ecosystem — Self-Hosting Installer
# Usage: curl -fsSL https://raw.githubusercontent.com/summitflow-solutions/summitflow/main/docker/install.sh | bash
set -euo pipefail

INSTALL_DIR="${INSTALL_DIR:-$HOME/summitflow-docker}"

echo "============================================"
echo "  SummitFlow Ecosystem — Self-Host Installer"
echo "============================================"
echo ""

# ─── Prerequisites ───────────────────────────────────────────────

check_command() {
  if ! command -v "$1" &>/dev/null; then
    echo "ERROR: $1 is not installed."
    echo "Install it and re-run this script."
    exit 1
  fi
}

check_command docker
check_command curl
check_command openssl
check_command jq

# Verify Docker Compose v2
if ! docker compose version &>/dev/null; then
  echo "ERROR: Docker Compose v2 plugin not found."
  echo "Install Docker Compose: https://docs.docker.com/compose/install/"
  exit 1
fi

echo "Docker: $(docker --version)"
echo "Compose: $(docker compose version)"
echo ""

# ─── Profile Selection ───────────────────────────────────────────

echo "Which projects do you want to run?"
echo "  1) SummitFlow only"
echo "  2) SummitFlow + Agent Hub"
echo "  3) Full stack (all projects)"
echo ""
read -rp "Select [1-3, default: 3]: " CHOICE
CHOICE="${CHOICE:-3}"

PROFILES=()
case "$CHOICE" in
  1) PROFILES=(--profile summitflow) ;;
  2) PROFILES=(--profile summitflow --profile agent-hub) ;;
  3) PROFILES=(--profile full) ;;
  *) echo "Invalid choice"; exit 1 ;;
esac

# ─── Generate Passwords ─────────────────────────────────────────

gen_password() {
  openssl rand -base64 24 | tr -d '/+=' | head -c 24
}

gen_secret() {
  openssl rand -base64 32
}

POSTGRES_PASSWORD=$(gen_password)
SF_DB_PASSWORD=$(gen_password)
AH_DB_PASSWORD=$(gen_password)
PA_DB_PASSWORD=$(gen_password)
REDIS_PASSWORD=$(gen_password)
AGENT_HUB_ENCRYPTION_KEY=$(gen_secret)
AGENT_HUB_SECRET_KEY=$(gen_secret)
INTERNAL_SERVICE_SECRET=$(gen_secret)

# Detect host Docker group GID (for Docker socket access in containers)
DOCKER_GID=$(getent group docker 2>/dev/null | cut -d: -f3 || stat -c '%g' /var/run/docker.sock 2>/dev/null || echo "990")

# ─── Setup Directory ────────────────────────────────────────────

echo ""
echo "Installing to: $INSTALL_DIR"
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

# Download compose files
REPO_BASE="https://raw.githubusercontent.com/summitflow-solutions/summitflow/main/docker/compose"
echo "Downloading compose files..."
curl -fsSL "$REPO_BASE/docker-compose.yml" -o docker-compose.yml
curl -fsSL "$REPO_BASE/init-db.sh" -o init-db.sh
curl -fsSL "$REPO_BASE/redis.conf" -o redis.conf
curl -fsSL "$REPO_BASE/.env.example" -o .env.example

# Download schema SQL files
for schema in summitflow-schema.sql agent-hub-schema.sql portfolio-ai-schema.sql; do
  echo "  Downloading $schema..."
  curl -fsSL "$REPO_BASE/$schema" -o "$schema" 2>/dev/null || echo "  Warning: $schema not found (may not be needed for your profile)"
done

chmod +x init-db.sh

# ─── Generate .env ───────────────────────────────────────────────

cat > .env <<EOF
# Generated by SummitFlow installer on $(date -Iseconds)
# IMPORTANT: Never run "docker compose down -v" — it destroys all data volumes.

# ─── Infrastructure ──────────────────────────────────────────────
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
SF_DB_PASSWORD=$SF_DB_PASSWORD
AH_DB_PASSWORD=$AH_DB_PASSWORD
PA_DB_PASSWORD=$PA_DB_PASSWORD
REDIS_PASSWORD=$REDIS_PASSWORD
TAG=latest
HATCHET_TAG=latest
DOCKER_GID=$DOCKER_GID

# ─── Host Configuration ─────────────────────────────────────────
HOST_HOME_PATH=$HOME

# ─── Backup / SMB ───────────────────────────────────────────────
# Set these to your SMB backup target
SMB_HOST=
SMB_SHARE=

# ─── Agent Hub Secrets ───────────────────────────────────────────
AGENT_HUB_ENCRYPTION_KEY=$AGENT_HUB_ENCRYPTION_KEY
AGENT_HUB_SECRET_KEY=$AGENT_HUB_SECRET_KEY
INTERNAL_SERVICE_SECRET=$INTERNAL_SERVICE_SECRET

# ─── Client Credentials (auto-generated below) ──────────────────
SUMMITFLOW_CLIENT_ID=
SUMMITFLOW_REQUEST_SOURCE=summitflow
AGENT_HUB_DASHBOARD_CLIENT_ID=
AGENT_HUB_DASHBOARD_REQUEST_SOURCE=agent-hub-dashboard
PORTFOLIO_CLIENT_ID=
PORTFOLIO_REQUEST_SOURCE=portfolio-ai
MONKEY_FIGHT_CLIENT_ID=
MONKEY_FIGHT_REQUEST_SOURCE=monkey-fight

# ─── Hatchet ──────────────────────────────────────────────────
# Config auto-generated by hatchet-setup-config into hatchet-config/ on first run.
HATCHET_CLIENT_TOKEN=

# ─── Optional API Keys ──────────────────────────────────────────
# ANTHROPIC_API_KEY=
# OPENAI_API_KEY=
EOF

chmod 600 .env
echo "Generated .env with random passwords and secrets"

# Create hatchet-config dir (setup-config will auto-generate keys on first run)
mkdir -p hatchet-config

# ─── Pull & Start ───────────────────────────────────────────────

echo ""
echo "Pulling images (this may take a few minutes)..."
docker compose "${PROFILES[@]}" pull

echo ""
echo "Starting services..."
docker compose "${PROFILES[@]}" up -d

# ─── Wait for Health ────────────────────────────────────────────

echo ""
echo "Waiting for services to become healthy..."

wait_for_service() {
  local name="$1" url="$2" timeout_secs="${3:-120}"
  local elapsed=0
  while [ $elapsed -lt "$timeout_secs" ]; do
    if curl -sf "$url" &>/dev/null; then
      echo "  $name is healthy"
      return 0
    fi
    sleep 2
    elapsed=$((elapsed + 2))
  done
  echo "  WARNING: $name did not become healthy within ${timeout_secs}s"
  return 1
}

apply_hatchet_tuning() {
  local server_file="hatchet-config/server.yaml"
  local database_file="hatchet-config/database.yaml"
  local changed=0

  if [ ! -f "$server_file" ] || [ ! -f "$database_file" ]; then
    echo "  WARNING: Hatchet config files not found; skipping runtime tuning."
    return 0
  fi

  update_yaml_value() {
    local file="$1" key="$2" value="$3"
    if grep -qE "^[[:space:]]*${key}: ${value}\$" "$file"; then
      return 0
    fi
    sed -i -E "s|^([[:space:]]*${key}:).*|\1 ${value}|" "$file"
    changed=1
  }

  update_yaml_value "$server_file" "schedulerConcurrencyPollingMinInterval" "1000000000"
  update_yaml_value "$database_file" "maxConns" "20"
  update_yaml_value "$database_file" "maxQueueConns" "20"
  update_yaml_value "$database_file" "minQueueConns" "3"

  if [ "$changed" -eq 0 ]; then
    echo "Hatchet runtime tuning already applied"
    return 0
  fi

  echo "Recreating Hatchet with tuned runtime config..."
  docker compose up -d --force-recreate hatchet
  wait_for_service "Hatchet" "http://localhost:8888/ready" 90
}

wait_for_service "Hatchet" "http://localhost:8888/ready" 90
apply_hatchet_tuning

# ─── Generate Hatchet Client Token ────────────────────────────

echo ""
echo "Generating Hatchet client token..."

TENANT_ID=""

# Query the Hatchet database for the default tenant
TENANT_ID=$(docker compose exec -T postgres psql -U admin -d hatchet -t -A \
  -c "SELECT id FROM \"Tenant\" LIMIT 1" 2>/dev/null | tr -d '[:space:]' || true)

if [ -z "$TENANT_ID" ]; then
  echo "  WARNING: Could not discover Hatchet tenant ID."
  echo "  After installation, generate a token manually:"
  echo "    docker compose run --rm --no-deps hatchet-setup-config /hatchet/hatchet-admin token create --config /hatchet/config --tenant-id <UUID>"
else
  HATCHET_TOKEN=$(docker compose run --rm --no-deps hatchet-setup-config \
    /hatchet/hatchet-admin token create --config /hatchet/config \
    --tenant-id "$TENANT_ID" --expiresIn 87600h 2>/dev/null \
    | grep -oE 'eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+' || true)

  if [ -n "$HATCHET_TOKEN" ]; then
    sed -i "s|^HATCHET_CLIENT_TOKEN=.*|HATCHET_CLIENT_TOKEN=$HATCHET_TOKEN|" .env
    echo "  Hatchet token generated and saved to .env"
  else
    echo "  WARNING: Hatchet token generation failed. Generate manually after installation."
  fi
fi

# Restart services to pick up Hatchet token
echo "Restarting services with Hatchet token..."
docker compose "${PROFILES[@]}" up -d

# ─── Auto-generate Client Credentials ────────────────────────────

if [[ "$CHOICE" == "2" || "$CHOICE" == "3" ]]; then
  wait_for_service "Agent Hub API" "http://localhost:8003/health" 60

  create_client() {
    local display_name="$1" env_var="$2" client_type="${3:-external}"
    local response client_id
    response=$(curl -sf -X POST "http://localhost:8003/api/access-control/clients" \
      -H "Content-Type: application/json" \
      -d "{\"display_name\": \"$display_name\", \"client_type\": \"$client_type\"}" 2>/dev/null) || true

    if [ -n "$response" ]; then
      client_id=$(echo "$response" | jq -r '.client_id // empty')
      if [ -n "$client_id" ]; then
        sed -i "s|^${env_var}=.*|${env_var}=$client_id|" .env
        echo "  Created client '$display_name' → $client_id"
        return 0
      fi
    fi
    echo "  WARNING: Failed to create client '$display_name'"
    return 1
  }

  echo ""
  echo "Creating client credentials in Agent Hub..."
  create_client "summitflow" "SUMMITFLOW_CLIENT_ID" "internal"
  create_client "agent-hub-dashboard" "AGENT_HUB_DASHBOARD_CLIENT_ID" "internal"

  if [[ "$CHOICE" == "3" ]]; then
    create_client "portfolio-ai" "PORTFOLIO_CLIENT_ID" "internal"
    create_client "monkey-fight" "MONKEY_FIGHT_CLIENT_ID" "external"
  fi

  # Restart services to pick up client IDs
  echo "Restarting services with client credentials..."
  docker compose "${PROFILES[@]}" up -d
fi

# ─── Final Health Check ──────────────────────────────────────────

echo ""
echo "Running final health checks..."
sleep 5
wait_for_service "SummitFlow API" "http://localhost:8001/health" 30 || true

if [[ "$CHOICE" == "2" || "$CHOICE" == "3" ]]; then
  wait_for_service "Agent Hub API" "http://localhost:8003/health" 30 || true
fi

# ─── Done ─────────────────────────────────────────────────────────

echo ""
echo "============================================"
echo "  Installation Complete!"
echo "============================================"
echo ""
echo "Access your services:"
echo "  SummitFlow:   http://localhost:3001"

if [[ "$CHOICE" == "2" || "$CHOICE" == "3" ]]; then
  echo "  Agent Hub:    http://localhost:3003"
fi

if [[ "$CHOICE" == "3" ]]; then
  echo "  Terminal:     http://localhost:3002"
  echo "  Portfolio AI: http://localhost:3000"
  echo "  Monkey Fight: http://localhost:4001"
fi

echo ""
echo "(Optional) Configure SMB backup target:"
echo "  Set SMB_HOST and SMB_SHARE in .env"
echo ""
echo "Management:"
echo "  Status:   docker compose ps"
echo "  Logs:     docker compose logs -f <service>"
echo "  Stop:     docker compose down"
echo "  Update:   docker compose pull && docker compose up -d"
echo "  DANGER:   Never use 'docker compose down -v' (destroys all data)"
echo ""
echo "Config:    $INSTALL_DIR/.env"
echo "Data:      Docker volumes (pgdata, redis-data), hatchet-config/"
echo ""
