#!/bin/bash
# SummitFlow Ecosystem — Self-Hosting Installer
# Usage: curl -fsSL https://raw.githubusercontent.com/summitflow-solutions/summitflow/main/docker/install.sh | bash
set -euo pipefail

COMPOSE_VERSION="latest"
INSTALL_DIR="${INSTALL_DIR:-$HOME/summitflow-docker}"

echo "============================================"
echo "  SummitFlow Ecosystem — Self-Host Installer"
echo "============================================"
echo ""

# ─── Prerequisites ───────────────────────────────────────────────

check_command() {
  if ! command -v "$1" &>/dev/null; then
    echo "ERROR: $1 is not installed."
    echo "Install it and re-run this script."
    exit 1
  fi
}

check_command docker
check_command curl
check_command openssl

# Verify Docker Compose v2
if ! docker compose version &>/dev/null; then
  echo "ERROR: Docker Compose v2 plugin not found."
  echo "Install Docker Compose: https://docs.docker.com/compose/install/"
  exit 1
fi

echo "Docker: $(docker --version)"
echo "Compose: $(docker compose version)"
echo ""

# ─── Profile Selection ───────────────────────────────────────────

echo "Which projects do you want to run?"
echo "  1) SummitFlow only"
echo "  2) SummitFlow + Agent Hub"
echo "  3) Full stack (all projects)"
echo ""
read -rp "Select [1-3, default: 3]: " CHOICE
CHOICE="${CHOICE:-3}"

case "$CHOICE" in
  1) PROFILE="summitflow" ;;
  2) PROFILE="summitflow --profile agent-hub" ;;
  3) PROFILE="full" ;;
  *) echo "Invalid choice"; exit 1 ;;
esac

# ─── Generate Passwords ─────────────────────────────────────────

gen_password() {
  openssl rand -base64 24 | tr -d '/+=' | head -c 24
}

gen_secret() {
  openssl rand -base64 32
}

POSTGRES_PASSWORD=$(gen_password)
SF_DB_PASSWORD=$(gen_password)
AH_DB_PASSWORD=$(gen_password)
PA_DB_PASSWORD=$(gen_password)
REDIS_PASSWORD=$(gen_password)
AGENT_HUB_ENCRYPTION_KEY=$(gen_secret)
AGENT_HUB_SECRET_KEY=$(gen_secret)
INTERNAL_SERVICE_SECRET=$(gen_secret)

# ─── Setup Directory ────────────────────────────────────────────

echo ""
echo "Installing to: $INSTALL_DIR"
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

# Download compose files
REPO_BASE="https://raw.githubusercontent.com/summitflow-solutions/summitflow/main/docker/compose"
echo "Downloading compose files..."
curl -fsSL "$REPO_BASE/docker-compose.yml" -o docker-compose.yml
curl -fsSL "$REPO_BASE/init-db.sh" -o init-db.sh
curl -fsSL "$REPO_BASE/redis.conf" -o redis.conf
curl -fsSL "$REPO_BASE/.env.example" -o .env.example

# Download schema SQL files
for schema in summitflow-schema.sql agent-hub-schema.sql portfolio-ai-schema.sql; do
  echo "  Downloading $schema..."
  curl -fsSL "$REPO_BASE/$schema" -o "$schema" 2>/dev/null || echo "  Warning: $schema not found (may not be needed for your profile)"
done

chmod +x init-db.sh

# ─── Generate .env ───────────────────────────────────────────────

cat > .env <<EOF
# Generated by SummitFlow installer on $(date -Iseconds)

# ─── Infrastructure ──────────────────────────────────────────────
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
SF_DB_PASSWORD=$SF_DB_PASSWORD
AH_DB_PASSWORD=$AH_DB_PASSWORD
PA_DB_PASSWORD=$PA_DB_PASSWORD
REDIS_PASSWORD=$REDIS_PASSWORD
TAG=latest
HATCHET_TAG=latest

# ─── Host Configuration ─────────────────────────────────────────
HOST_HOME_PATH=$HOME

# ─── Backup / SMB ───────────────────────────────────────────────
# Set these to your SMB backup target
SMB_HOST=
SMB_SHARE=

# ─── Agent Hub Secrets ───────────────────────────────────────────
AGENT_HUB_ENCRYPTION_KEY=$AGENT_HUB_ENCRYPTION_KEY
AGENT_HUB_SECRET_KEY=$AGENT_HUB_SECRET_KEY
INTERNAL_SERVICE_SECRET=$INTERNAL_SERVICE_SECRET

# ─── Client Credentials (fill in after first boot) ──────────────
# Generate these in the Agent Hub dashboard after services are running.
SUMMITFLOW_CLIENT_ID=
SUMMITFLOW_CLIENT_SECRET=
AGENT_HUB_DASHBOARD_CLIENT_ID=
AGENT_HUB_DASHBOARD_CLIENT_SECRET=
PORTFOLIO_CLIENT_ID=
PORTFOLIO_CLIENT_SECRET=
MONKEY_FIGHT_CLIENT_ID=
MONKEY_FIGHT_CLIENT_SECRET=

# ─── Hatchet ────────────────────────────────────────────────────
# Generate after first boot:
#   docker compose exec hatchet /hatchet-admin token create --config /config --tenant-id <UUID>
HATCHET_CLIENT_TOKEN=

# ─── Optional API Keys ──────────────────────────────────────────
# ANTHROPIC_API_KEY=
# OPENAI_API_KEY=
EOF

echo "Generated .env with random passwords and secrets"

# ─── Pull & Start ───────────────────────────────────────────────

echo ""
echo "Pulling images (this may take a few minutes)..."
docker compose --profile "$PROFILE" pull

echo ""
echo "Starting services..."
docker compose --profile "$PROFILE" up -d

# ─── Wait for Health ────────────────────────────────────────────

echo ""
echo "Waiting for services to become healthy..."
for i in $(seq 1 60); do
  if curl -sf http://localhost:8001/health &>/dev/null; then
    break
  fi
  sleep 2
done

# ─── Post-boot: Hatchet Token ──────────────────────────────────

echo ""
echo "============================================"
echo "  Installation Complete!"
echo "============================================"
echo ""
echo "Access your services:"
echo "  SummitFlow:   http://localhost:3001"

if [[ "$CHOICE" == "2" || "$CHOICE" == "3" ]]; then
  echo "  Agent Hub:    http://localhost:3003"
fi

if [[ "$CHOICE" == "3" ]]; then
  echo "  Terminal:     http://localhost:3002"
  echo "  Portfolio AI: http://localhost:3000"
  echo "  Monkey Fight: http://localhost:4001"
fi

echo ""
echo "─── Post-Boot Steps ────────────────────────"
echo ""
echo "1. Generate Hatchet token:"
echo "   docker compose exec hatchet /hatchet-admin token create --config /config --tenant-id <UUID>"
echo "   Then add to .env as HATCHET_CLIENT_TOKEN and restart workers:"
echo "   docker compose restart summitflow-worker agent-hub-worker portfolio-worker"
echo ""
echo "2. Set up client credentials in Agent Hub, then update .env with"
echo "   the CLIENT_ID and CLIENT_SECRET values for each project."
echo ""
echo "3. (Optional) Configure SMB backup target:"
echo "   Set SMB_HOST and SMB_SHARE in .env"
echo ""
echo "Management:"
echo "  Status:  docker compose ps"
echo "  Logs:    docker compose logs -f <service>"
echo "  Stop:    docker compose down"
echo "  Update:  docker compose pull && docker compose up -d"
echo ""
echo "Config:    $INSTALL_DIR/.env"
echo "Data:      Docker volumes (pgdata, redis-data)"
echo ""
