import { render, screen } from '@testing-library/react'
import { describe, expect, it } from 'vitest'
import { NeedsAttentionCard } from './NeedsAttentionCard'

describe('NeedsAttentionCard', () => {
  it('surfaces escalated issues and hidden overflow counts', () => {
    render(
      <NeedsAttentionCard
        items={[
          {
            id: 1,
            project_id: 'summitflow',
            check_type: 'ruff',
            check_name: 'Ruff',
            status: 'failed',
            error_count: 3,
            warning_count: 0,
            error_message: null,
            file_path: '/repo/frontend/app/page.tsx',
            line_number: 14,
            column_number: null,
            run_duration_ms: null,
            git_sha: null,
            triggered_by: null,
            fix_attempted: true,
            fix_attempts: 2,
            fixed_at: null,
            fixed_by: null,
            created_at: '2026-03-11T12:00:00Z',
            updated_at: '2026-03-11T12:00:00Z',
            escalation_task_id: 'task-123',
          },
          {
            id: 2,
            project_id: 'summitflow',
            check_type: 'types',
            check_name: 'Types',
            status: 'failed',
            error_count: 1,
            warning_count: 0,
            error_message: null,
            file_path: '/repo/frontend/components/health/FixPipelineCard.tsx',
            line_number: 22,
            column_number: null,
            run_duration_ms: null,
            git_sha: null,
            triggered_by: null,
            fix_attempted: false,
            fix_attempts: 0,
            fixed_at: null,
            fixed_by: null,
            created_at: '2026-03-11T12:00:00Z',
            updated_at: '2026-03-11T12:00:00Z',
            escalation_task_id: null,
          },
          {
            id: 3,
            project_id: 'summitflow',
            check_type: 'pytest',
            check_name: 'Pytest',
            status: 'failed',
            error_count: 1,
            warning_count: 0,
            error_message: null,
            file_path: '/repo/backend/tests/api/test_projects.py',
            line_number: 48,
            column_number: null,
            run_duration_ms: null,
            git_sha: null,
            triggered_by: null,
            fix_attempted: false,
            fix_attempts: 0,
            fixed_at: null,
            fixed_by: null,
            created_at: '2026-03-11T12:00:00Z',
            updated_at: '2026-03-11T12:00:00Z',
            escalation_task_id: null,
          },
          {
            id: 4,
            project_id: 'summitflow',
            check_type: 'biome',
            check_name: 'Biome',
            status: 'failed',
            error_count: 1,
            warning_count: 0,
            error_message: null,
            file_path: '/repo/frontend/components/dashboard/ProjectCard.tsx',
            line_number: 77,
            column_number: null,
            run_duration_ms: null,
            git_sha: null,
            triggered_by: null,
            fix_attempted: false,
            fix_attempts: 0,
            fixed_at: null,
            fixed_by: null,
            created_at: '2026-03-11T12:00:00Z',
            updated_at: '2026-03-11T12:00:00Z',
            escalation_task_id: null,
          },
          {
            id: 5,
            project_id: 'summitflow',
            check_type: 'sqlfluff',
            check_name: 'SQLFluff',
            status: 'failed',
            error_count: 1,
            warning_count: 0,
            error_message: null,
            file_path: '/repo/backend/alembic/versions/demo.py',
            line_number: 11,
            column_number: null,
            run_duration_ms: null,
            git_sha: null,
            triggered_by: null,
            fix_attempted: false,
            fix_attempts: 0,
            fixed_at: null,
            fixed_by: null,
            created_at: '2026-03-11T12:00:00Z',
            updated_at: '2026-03-11T12:00:00Z',
            escalation_task_id: null,
          },
          {
            id: 6,
            project_id: 'summitflow',
            check_type: 'ruff',
            check_name: 'Ruff',
            status: 'failed',
            error_count: 1,
            warning_count: 0,
            error_message: null,
            file_path: '/repo/backend/app/main.py',
            line_number: 90,
            column_number: null,
            run_duration_ms: null,
            git_sha: null,
            triggered_by: null,
            fix_attempted: false,
            fix_attempts: 0,
            fixed_at: null,
            fixed_by: null,
            created_at: '2026-03-11T12:00:00Z',
            updated_at: '2026-03-11T12:00:00Z',
            escalation_task_id: null,
          },
        ]}
      />,
    )

    expect(screen.getByText('Escalated')).toBeInTheDocument()
    expect(screen.getByText('+1 more unresolved issues')).toBeInTheDocument()
    expect(screen.getByText('app/page.tsx')).toBeInTheDocument()
  })
})
