"""drop dead tables

Revision ID: 8c443d64b9a7
Revises: fd955094f350
Create Date: 2026-03-11 12:02:12.425952

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c443d64b9a7"
down_revision: str | Sequence[str] | None = "fd955094f350"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("DROP TABLE IF EXISTS model_performance_logs")
    op.execute("DROP TABLE IF EXISTS model_performance_metrics")
    op.execute("DROP TABLE IF EXISTS migration_backup")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS model_performance_logs (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            task_id TEXT,
            model_name TEXT NOT NULL,
            task_type TEXT NOT NULL,
            complexity TEXT NOT NULL,
            outcome TEXT NOT NULL,
            quality_score DOUBLE PRECISION,
            tokens_used INTEGER,
            latency_ms INTEGER,
            error_category TEXT,
            metadata JSONB DEFAULT '{}'::jsonb,
            created_at TIMESTAMPTZ DEFAULT NOW()
        )
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_model_perf_logs_created_at
        ON model_performance_logs(created_at DESC)
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_model_perf_logs_lookup
        ON model_performance_logs(model_name, task_type, complexity)
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_model_perf_logs_task_id
        ON model_performance_logs(task_id)
        """
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS model_performance_metrics (
            model_name TEXT NOT NULL,
            task_type TEXT NOT NULL,
            complexity TEXT NOT NULL,
            success_count INTEGER DEFAULT 0,
            failure_count INTEGER DEFAULT 0,
            total_executions INTEGER DEFAULT 0,
            avg_quality_score DOUBLE PRECISION DEFAULT 0.0,
            avg_latency_ms DOUBLE PRECISION DEFAULT 0.0,
            avg_tokens_used DOUBLE PRECISION DEFAULT 0.0,
            last_executed_at TIMESTAMPTZ,
            updated_at TIMESTAMPTZ DEFAULT NOW(),
            PRIMARY KEY (model_name, task_type, complexity)
        )
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_model_perf_metrics_ranking
        ON model_performance_metrics(task_type, complexity, success_count DESC, avg_quality_score DESC)
        """
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS migration_backup (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            migration_name TEXT NOT NULL,
            table_name TEXT NOT NULL,
            row_id TEXT NOT NULL,
            original_data JSONB NOT NULL,
            migrated_at TIMESTAMPTZ DEFAULT NOW()
        )
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_migration_backup_name
        ON migration_backup(migration_name)
        """
    )
