#!/usr/bin/env bash

PROJECT_ROOTS_WORKSPACES_ROOT="${ST_WORKSPACES_ROOT:-/srv/workspaces}"
PROJECT_ROOTS_MANAGED_REPOS_FILE="${PROJECT_ROOTS_MANAGED_REPOS_FILE:-$HOME/.claude/config/managed-repos.txt}"

project_root_ids_static() {
    printf '%s\n' summitflow agent-hub portfolio-ai terminal monkey-fight
}

project_root_ids() {
    command -v st >/dev/null 2>&1 || {
        project_root_ids_static
        return 0
    }

    local project_ids
    project_ids="$(
        ST_PROGRESS_ONLY=1 st projects list 2>/dev/null | python3 -c '
import json, sys
try:
    payload = json.load(sys.stdin)
except Exception:
    sys.exit(1)
if not isinstance(payload, list):
    sys.exit(1)
for item in payload:
    if isinstance(item, dict):
        project_id = item.get("id")
        if project_id:
            print(project_id)
' 2>/dev/null
    )" || true

    if [ -n "$project_ids" ]; then
        printf '%s\n' "$project_ids"
        return 0
    fi

    project_root_ids_static
}

project_root_from_cli() {
    local project="$1"

    command -v st >/dev/null 2>&1 || return 1

    local root_path
    root_path="$(ST_PROGRESS_ONLY=1 st projects root "$project" 2>/dev/null | head -n 1 | tr -d '\r')"
    [ -n "$root_path" ] || return 1
    printf '%s\n' "$root_path"
}

default_home_root_for_project() {
    case "$1" in
        summitflow)
            [ -n "${SUMMITFLOW_ROOT_OVERRIDE:-}" ] || return 1
            printf '%s\n' "$SUMMITFLOW_ROOT_OVERRIDE"
            ;;
        agent-hub | portfolio-ai | terminal | monkey-fight)
            printf '%s\n' "$HOME/$1"
            ;;
        *)
            return 1
            ;;
    esac
}

shared_workspaces_root() {
    printf '%s\n' "$PROJECT_ROOTS_WORKSPACES_ROOT"
}

shared_cache_root() {
    printf '%s\n' "$(shared_workspaces_root)/cache"
}

shared_cache_dir() {
    local cache_name="$1"
    printf '%s\n' "$(shared_cache_root)/$cache_name"
}

resolve_project_root() {
    local project="$1"
    local candidate

    if [ "$project" = "summitflow" ] && [ -n "${SUMMITFLOW_ROOT_OVERRIDE:-}" ] && [ -d "${SUMMITFLOW_ROOT_OVERRIDE}" ]; then
        printf '%s\n' "$SUMMITFLOW_ROOT_OVERRIDE"
        return 0
    fi

    candidate="$(project_root_from_cli "$project" 2>/dev/null || true)"
    if [ -n "$candidate" ] && [ -d "$candidate" ]; then
        printf '%s\n' "$candidate"
        return 0
    fi

    candidate="${PROJECT_ROOTS_WORKSPACES_ROOT}/projects/$project"
    if [ -d "$candidate" ]; then
        printf '%s\n' "$candidate"
        return 0
    fi

    candidate="$(default_home_root_for_project "$project" 2>/dev/null || true)"
    if [ -n "$candidate" ] && [ -d "$candidate" ]; then
        printf '%s\n' "$candidate"
        return 0
    fi

    return 1
}

list_managed_repo_paths() {
    local project
    local candidate

    {
        while IFS= read -r project; do
            [ -n "$project" ] || continue
            candidate="$(resolve_project_root "$project" 2>/dev/null || true)"
            if [ -n "$candidate" ] && [ -d "$candidate/.git" ]; then
                printf '%s\n' "$candidate"
            fi
        done < <(project_root_ids)

        for candidate in "$HOME/.claude" "$HOME/.codex" "$HOME/persona-sandbox"; do
            if [ -d "$candidate/.git" ]; then
                printf '%s\n' "$candidate"
            fi
        done
    } | awk '!seen[$0]++'
}

write_managed_repo_file() {
    local target="${1:-$PROJECT_ROOTS_MANAGED_REPOS_FILE}"
    local target_dir
    target_dir="$(dirname "$target")"
    mkdir -p "$target_dir"

    {
        printf '# Managed Git Repositories\n'
        printf '# Auto-generated by SummitFlow setup-services.sh. Do not edit by hand.\n'
        printf '# Used as fallback when the SummitFlow API is unavailable.\n\n'
        list_managed_repo_paths
    } > "$target"
}
