#!/bin/bash
# Creates databases, users, extensions, and schemas for all projects.
# Mounted as /docker-entrypoint-initdb.d/init-db.sh — runs once on fresh volume.
set -e

INIT_DIR="/docker-entrypoint-initdb.d"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  -- Create application users
  CREATE USER summitflow_app WITH PASSWORD '${SF_DB_PASSWORD:-changeme}';
  CREATE USER agent_hub_app WITH PASSWORD '${AH_DB_PASSWORD:-changeme}';
  CREATE USER portfolio_app WITH PASSWORD '${PA_DB_PASSWORD:-changeme}';

  -- Create project databases owned by their app users
  CREATE DATABASE summitflow OWNER summitflow_app;
  CREATE DATABASE agent_hub OWNER agent_hub_app;
  CREATE DATABASE portfolio_ai OWNER portfolio_app;
  CREATE DATABASE hatchet;

  -- Test databases (for pytest)
  CREATE DATABASE summitflow_test OWNER summitflow_app;
  CREATE DATABASE agent_hub_test OWNER agent_hub_app;
  CREATE DATABASE portfolio_ai_test OWNER portfolio_app;
EOSQL

# Create extensions as superuser (app users can't do this)
for db in summitflow agent_hub portfolio_ai summitflow_test agent_hub_test portfolio_ai_test; do
  psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -d "$db" -c \
    "CREATE EXTENSION IF NOT EXISTS vector; CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";" 2>/dev/null || true
done

# Apply schema dumps (generated by: db dump all-schemas <dir>)
apply_schema() {
  local db="$1" user="$2" file="$3"
  if [ -f "$file" ]; then
    echo "Applying $db schema from $(basename "$file")..."
    # Strip extension/comment lines (already created above as superuser)
    grep -v "CREATE EXTENSION\|COMMENT ON EXTENSION" "$file" | \
      psql -v ON_ERROR_STOP=1 --username "$user" -d "$db"
    echo "$db schema applied."
  fi
}

apply_schema summitflow summitflow_app "$INIT_DIR/summitflow-schema.sql"
apply_schema agent_hub agent_hub_app "$INIT_DIR/agent-hub-schema.sql"
apply_schema portfolio_ai portfolio_app "$INIT_DIR/portfolio-ai-schema.sql"

echo "Database initialization complete."
